site_name: Michael Taylor â€“ Documentation Platform
site_description: Documentation as Platform Architecture Demo
site_author: Michael Taylor

theme:
  name: material

docs_dir: docs
site_dir: site

nav:
  - Home: index.md