site_name: Michael Taylor â€“ Documentation Systems Portfolio
site_description: Documentation as Platform Architecture Demo
site_author: Michael Taylor

theme:
  name: material
  features:
    - content.code.copy

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - admonition
  - toc:
      permalink: true

docs_dir: docs
site_dir: site

nav:
  - Home: index.md

  - Portfolio Architecture:
      - Overview: architecture/platform-architecture.md

  - Engineering Projects:
      - unstructured-framemaker-dita/unstructured-framemaker-to-dita.md
      - CMS Platform: 
          - projects/cms-platform/cms-platform-overview.md
          - projects/cms-platform/cms-architecture.md

          - Power App Architecture:
              - projects/cms-platform/power-app-design/PowerApp_Standalone_DesignDoc.md
              - Feature Modules:
                  - projects/cms-platform/power-app-design/power-app-features/ScreenBreakdownAndLogic.md
                  - projects/cms-platform/power-app-design/power-app-features/DelegableFilteringAndSearching.md
                  - projects/cms-platform/power-app-design/power-app-features/ArticleVersioningFeature.md
                  - projects/cms-platform/power-app-design/power-app-features/ArchivedHistoryManagement.md
                  - projects/cms-platform/power-app-design/power-app-features/GenericUIComponents.md
                  - projects/cms-platform/power-app-design/power-app-features/UIUXBestPractices.md
                  - projects/cms-platform/power-app-design/power-app-features/TroubleshootingAndKeyFixes.md
                  - projects/cms-platform/power-app-design/power-app-features/AdvancedTroubleshooting.md

          - Power Automate Flows:
              - projects/cms-platform/power-automate-flows/flow-designs/Instant_-_Create_New_Article_Version.md
              - projects/cms-platform/power-automate-flows/flow-designs/Instant_-_Discard_Article_Draft.md
              - projects/cms-platform/power-automate-flows/flow-designs/Instant_-_Expire_Single_KB_Article_v2.md
              - projects/cms-platform/power-automate-flows/flow-designs/Instant_-_Manage_SME_Approval.md
              - projects/cms-platform/power-automate-flows/flow-designs/Instant_-_Reactivate_Archived_Article.md
              - projects/cms-platform/power-automate-flows/flow-designs/Instant_-_Revert_to_Version.md
              - projects/cms-platform/power-automate-flows/flow-designs/Instant_-_Start_KB_Article_Approval.md
              - projects/cms-platform/power-automate-flows/flow-designs/KB-API-Endpoint.md
              - projects/cms-platform/power-automate-flows/flow-designs/KB_ID_Generator_Child.md
              - projects/cms-platform/power-automate-flows/flow-designs/LogAuditEvent_designDoc.md
              - projects/cms-platform/power-automate-flows/flow-designs/LogSystemEvent_designDoc.md
              - projects/cms-platform/power-automate-flows/flow-designs/Notify-StrippedCharacter.md
              - projects/cms-platform/power-automate-flows/flow-designs/Orchestrate-GenerateAltTextAndSaveArticle.md
              - projects/cms-platform/power-automate-flows/flow-designs/Scheduled_-_Unassigned_Article_Reminder.md

          - GitHub Publishing:
              - projects/cms-platform/github-pipeline/github-architecture.md
              - Pipeline Design:
                 - projects/cms-platform/github-pipeline/elixir-kbarticle-dispatcher.md
                 - projects/cms-platform/github-pipeline/process-kb-repo.md
                 - projects/cms-platform/github-pipeline/elixir-kbarticle-publish-worker.md
                 - projects/cms-platform/github-pipeline/reusable-summarize-and-sync.md
                 - projects/cms-platform/github-pipeline/create-kb-met.md

  - Documentation Pipelines:
     - Pipeline Overview: pipelines/pipeline-overview.md
     - CI/CD Workflows:
        - pipelines/automatic-validation/elixir-automatic-file-validation.md
        - Scheduled External Link Validator: pipelines/external-link-validation/external-link-check.md
        - Automatic Workflow Sync Across Organization: pipelines/automatic-workflow-sync/sync-workflows.md
     - Automation Scripts:
        - File Content and Metadata Validator: pipelines/automatic-validation/file-validator.md
        - HTML File Renaming: pipelines/automatic-validation/file-rename.md
        - Create Metadata Files: pipelines/create-metadata-files/create-met-go.md
        - Create RSS Feed: pipelines/create-rss/create-rss.md
        - pipelines/standalone-guide-generator/standalone-guide-reference-processor.md

